micronaut:
  session:
    http:
      cookie: false
      header: true
      redis:
        enabled: true
  http:
    client:
      read-timeout: 1m

  application:
    name: farm_attic_api
  server:
    port: 8000
    cors:
      enabled: true
  security:
    enabled: true
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: 'cGxlYXNlQ2hhbmdlVGhpc1NlY3JldEZvckFOZXdPbmU='
              base64: true
    authentication: bearer

  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**

netty:
  default:
    allocator:
      max-order: 3


datasources:
  default:
    url: jdbc:postgresql://localhost:5432/postgresql?sslmode=disable
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    dialect : POSTGRES



flyway:
  datasources:
   default:
     enabled: true
     locations: 'classpath:db.migration'

jpa:
  default:
    entity-scan:
      packages: 'com.farmAttic.models'
    properties:
      hibernate:
        hbm2ddl:
          auto: validate
        show_sql: false
